In [1]:
from nltk.stem.snowball import SnowballStemmer
sn_stemmer=SnowballStemmer("english")
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import nltk
import pandas as pd
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [3]:
df = pd.read_csv('Restaurant_Reviews - Restaurant_Reviews.tsv',sep='\t')

In [5]:
def datacleaning(x):
#---------------------------------------------------------------------------------------------------------------------------    
    #Removing stop words.
    y=nltk.word_tokenize(x)
    temp=[]
    for i in y:
          if i in stopwords.words("english"): 
            pass
          else:
            temp.append(i)
    my_new_string=' '.join(temp)
#---------------------------------------------------------------------------------------------------------------------------        
    #Lemmatizing the data.
    c=nltk.word_tokenize(my_new_string)
    my_list=[]
    for i in c:
        my_list.append(lemmatizer.lemmatize(i))
        my_new_string_second=' '.join(my_list)
#---------------------------------------------------------------------------------------------------------------------------            
    #Stemming the data.
        d=nltk.word_tokenize(my_new_string_second)
    my_list_stemmer=[]
    for i in d:
        my_list_stemmer.append(sn_stemmer.stem(i))
        final=' '.join(my_list_stemmer)
#---------------------------------------------------------------------------------------------------------------------------  
    #Removing the numbers from the data.
        temp=[]
    for i in final:
        if i.isdigit(): 
             pass
        else:
            temp.append(i)
    hi=''.join(temp)
    return (hi.lower()) #Converting the data to lower case

In [6]:
df['Cleaned_review']=df['Review'].apply(datacleaning)

In [7]:
df

Review  Liked  \
0                             Wow... Loved this place.      1   
1                                   Crust is not good.      0   
2            Not tasty and the texture was just nasty.      0   
3    Stopped by during the late May bank holiday of...      1   
4    The selection on the menu was great and so wer...      1   
..                                                 ...    ...   
995  I think food should have flavor and texture an...      0   
996                           Appetite instantly gone.      0   
997  Overall I was not impressed and would not go b...      0   
998  The whole experience was underwhelming, and I ...      0   
999  Then, as if I hadn't wasted enough of my life ...      0   

                                        Cleaned_review  
0                                 wow ... love place .  
1                                         crust good .  
2                             not tasti textur nasti .  
3    stop late may bank holiday rick steve recommen...  
4                        the select menu great price .  
..                                                 ...  
995                  i think food flavor textur lack .  
996                             appetit instant gone .  
997                   overal i impress would go back .  
998  the whole experi underwhelm , i think ll go ni...  
999  then , i n't wast enough life , pour salt woun...  

[1000 rows x 3 columns]

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
#initializing the vector.
hi_vectorize = CountVectorizer()
hi_vectorize.fit(df['Cleaned_review'])

CountVectorizer()

In [9]:
 hi_vectorize.get_feature_names_out()[0:100]

array(['absolut', 'absolutley', 'accid', 'accommod', 'accomod', 'accord',
       'account', 'ach', 'acknowledg', 'across', 'actual', 'ad', 'afford',
       'after', 'afternoon', 'again', 'ago', 'ahead', 'airlin', 'airport',
       'al', 'ala', 'albondiga', 'all', 'allergi', 'almond', 'almost',
       'alon', 'also', 'although', 'alway', 'amaz', 'ambianc', 'ambienc',
       'amount', 'ampl', 'an', 'and', 'andddd', 'angri', 'ani', 'annoy',
       'anoth', 'anticip', 'anymor', 'anyon', 'anyth', 'anytim', 'anyway',
       'apart', 'apolog', 'app', 'appal', 'appar', 'appeal', 'appet',
       'appetit', 'appl', 'approv', 'are', 'area', 'arepa', 'aria',
       'around', 'array', 'arriv', 'articl', 'as', 'ask', 'assur', 'at',
       'ate', 'atmospher', 'atmosphere', 'atroci', 'attach', 'attack',
       'attent', 'attitud', 'auju', 'authent', 'averag', 'avocado',
       'avoid', 'aw', 'away', 'awesom', 'awkward', 'ayc', 'az', 'baba',
       'babi', 'bachi', 'back', 'bacon', 'bad', 'bagel', 'bak

In [10]:
my_vector=hi_vectorize.transform(df['Cleaned_review'])
my_array=my_vector.toarray()

In [11]:
my_array

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [12]:
my_vector

<1000x1623 sparse matrix of type '<class 'numpy.int64'>'
	with 5999 stored elements in Compressed Sparse Row format>

In [13]:
from sklearn.cluster import KMeans
import numpy as np

In [14]:
# Initialising
km = KMeans(n_clusters=5)

In [15]:
# Fitting a model
km_model = km.fit(my_vector)

In [16]:
# Making predictions
y_km = km.predict(my_vector)

In [17]:
# Let's see our predictions
y_km

array([0, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 4, 1, 1, 1, 4, 0, 0, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 3, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 0, 1, 3, 0, 1,
       2, 2, 1, 1, 1, 2, 1, 1, 0, 1, 2, 1, 2, 3, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 3, 3, 1, 1, 1, 3, 1, 1, 1, 4, 1, 1, 1, 3, 1,
       1, 1, 4, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 2, 1, 1, 2, 0, 1,
       1, 1, 1, 1, 1, 4, 4, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 4, 1, 1,
       1, 1, 1, 2, 0, 1, 3, 1, 1, 1, 1, 1, 0, 3, 1, 1, 1, 4, 1, 1, 1, 3,
       1, 1, 0, 4, 1, 3, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 2, 1, 0, 1, 1, 2, 1, 3, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 3, 1, 1, 4, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 3, 1, 2, 1,
       2, 1, 0, 4, 1, 0, 1, 3, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 2, 1, 1, 1, 3, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 2, 0, 0, 1, 1, 1, 3, 1, 1, 2, 1, 0, 1, 1,

In [18]:
km.cluster_centers_

array([[0.        , 0.        , 0.00970874, ..., 0.        , 0.        ,
        0.        ],
       [0.00960219, 0.00137174, 0.        , ..., 0.00274348, 0.00548697,
        0.00685871],
       [0.01960784, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.01333333, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])